name: team_aa_dap_2024
services:

  ## DAGSTER

  dagster:
    container_name: dagster_etl
    build: .
    ports:
      - "3000:3000"
    depends_on:
      mongodb:
        condition: service_started
      postgres:
        condition: service_healthy
    volumes:
      - ./output:/main/storage
      - ./dagster.yaml:/main/dagster.yaml
      - ./workspace.yaml:/main/workspace.yaml
    environment:
      POSTGRES_HOST: postgres_database
      POSTGRES_USER: ${USER:-dap}
      POSTGRES_PASSWORD: ${PASSWORD:-dap}
      POSTGRES_DB: postgres
      DAGSTER_HOME: /main
    command: dagster-webserver -h 0.0.0.0 -w workspace.yaml

  dagster_daemon:
    container_name: dagster_daemon
    build: .
    depends_on:
      mongodb:
        condition: service_started
      postgres:
        condition: service_healthy
    volumes:
      - ./output:/main/storage
      - ./dagster.yaml:/main/dagster.yaml
      - ./workspace.yaml:/main/workspace.yaml
    environment:
      POSTGRES_HOST: postgres_database
      POSTGRES_USER: ${USER:-dap}
      POSTGRES_PASSWORD: ${PASSWORD:-dap}
      POSTGRES_DB: postgres
      DAGSTER_HOME: /main
    command: dagster-daemon run

  ## MONGODB

  mongodb:
    image: "mongo"
    container_name: mongodb_database
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${USER:-dap}
      MONGO_INITDB_ROOT_PASSWORD: ${PASSWORD:-dap}
    ports:
      - 27017-27019:27017-27019
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  ## POSTGRES

  postgres:
    image: "postgres"
    container_name: postgres_database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${USER:-dap}
      POSTGRES_PASSWORD: ${PASSWORD:-dap}
    volumes:
      - postgres-data:/var/lib/postgresql
    configs:
      - source: createdb.sql
        target: /docker-entrypoint-initdb.d/createdb.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USER:-dap} -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  ## MONGO EXPRESS

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://${USER:-dap}:${PASSWORD:-dap}@mongodb:27017"
      ME_CONFIG_BASICAUTH_USERNAME: ${USER:-dap}
      ME_CONFIG_BASICAUTH_PASSWORD: ${PASSWORD:-dap}
    depends_on:
      - mongodb

  ## PGADMIN

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-dap@dap.com}
      PGADMIN_DEFAULT_PASSWORD: ${PASSWORD:-dap}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "5050:80"
    entrypoint: /bin/sh -c "chmod 600 /pgpass; /entrypoint.sh;"
    user: root
    configs:
      - source: servers.json
        target: /pgadmin4/servers.json
      - source: pgpass
        target: /pgpass
    restart: unless-stopped
    depends_on:
      - postgres

  ##JUPYTER

  jupyter:
    build:
      context: .
      dockerfile: ./jupyter/Dockerfile
    volumes:
      - ./analysis:/main
    ports:
      - 8888:8888
    environment:
      POSTGRES_HOST: postgres_database
    container_name: jupyter_notebook
    command: "start-notebook.sh --NotebookApp.token="

  ## DASHBORAD

  dashboard:
    container_name: dashboard
    build:
      context: .
      dockerfile: ./dashboard/Dockerfile
    volumes:
      - ./dashboard:/dashboard
    ports:
      - 5006:5006
    environment:
      POSTGRES_HOST: postgres_database
  ## CONFIGS

configs:
  pgpass:
    content: postgres:5432:*:${USER:-dap}:${PASSWORD:-dap}
  servers.json:
    content: |
      {
          "Servers": {
            "1": {
              "Name": "postgres",
              "Group": "Servers",
              "Host": "postgres",
              "Port": 5432,
              "MaintenanceDB": "postgres",
              "Username": "dap",
              "PassFile": "/pgpass",
              "SSLMode": "prefer"
            }
          }
        }
  createdb.sql:
    content: CREATE DATABASE projectdb;

volumes:
  postgres-data:
