name: team_aa_dap_2024
services:

  ## DAGSTER

  dashboard:
    container_name: dashboard
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/ankithbjoseph/teamaa-dashboard:latest
    ports:
      - "3000:3000"
      - "5006:5006"
    depends_on:
      mongodb:
        condition: service_started
      postgres:
        condition: service_healthy
    volumes:
      - ./output:/main/storage
      - ./dashboard:/main/dashboard
      - ./dagster.yaml:/main/dagster.yaml
      - ./workspace.yaml:/main/workspace.yaml


  ## MONGODB

  mongodb:
    image: "mongo"
    container_name: mongodb_database
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-example}
    ports:
      - 27017-27019:27017-27019
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  ## POSTGRES

  postgres:
    image: "postgres"
    container_name: postgres_database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-example}
    volumes:
      - postgres-data:/var/lib/postgresql
    configs:
      - source: createdb.sql
        target: /docker-entrypoint-initdb.d/createdb.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  ## MONGO EXPRESS

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://${MONGO_INITDB_ROOT_USERNAME:-root}:${MONGO_INITDB_ROOT_PASSWORD:-example}@${MONGO_HOST:-mongodb}:27017"
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-example}
    depends_on:
      - mongodb

  ## PGADMIN

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "5050:80"
    entrypoint: /bin/sh -c "chmod 600 /pgpass; /entrypoint.sh;"
    user: root
    configs:
      - source: servers.json
        target: /pgadmin4/servers.json
      - source: pgpass
        target: /pgpass
    restart: unless-stopped
    depends_on:
      - postgres

  ##JUPYTER

  jupyter:
    build:
      context: .
      dockerfile: ./jupyter/Dockerfile
    volumes:
      - ./analysis:/main
    ports:
      - 8888:8888
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
    container_name: jupyter_notebook
    command: "start-notebook.sh --NotebookApp.token="

  
  ## CONFIGS

configs:
  pgpass:
    content: postgres:5432:*:${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-example}
  servers.json:
    content: |
      {
          "Servers": {
            "1": {
              "Name": "postgres",
              "Group": "Servers",
              "Host": "${POSTGRES_HOST:-postgres}",
              "Port": ${POSTGRES_PORT:-5432},
              "MaintenanceDB": "${POSTGRES_DB:-postgres}",
              "Username": "${POSTGRES_USER:-postgres}",
              "PassFile": "/pgpass",
              "SSLMode": "prefer"
            }
          }
        }
  createdb.sql:
    content: CREATE DATABASE ${POSTGRES_DB_APP:-appdb};

volumes:
  postgres-data:
